apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfhost
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selfhost
  template:
    metadata:
      labels:
        app: selfhost
    spec:
      containers:
      - name: selfhost
        image: mcr.microsoft.com/azuredocs/aks-store-demo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: selfhost
  namespace: default
spec:
  selector:
    app: selfhost
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selfhost-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: webapprouting.kubernetes.io/ingress
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: itconpetstore.azurefd.us
    http:
      paths:
      - path: /selfhost
        pathType: Prefix
        backend:
          service:
            name: selfhost
            port:
              number: 80

